---
version: '3.6'

x-besu-def: &besu-def
  restart: "on-failure"
  image: hyperledger/besu:${BESU_VERSION:-latest}
  env_file:
    - ./config/besu/.env
  entrypoint:
    - /bin/bash
    - -c
    - |
      
      cp "/config/${BESU_CONS_ALGO:-QBFT}genesis.json" /config/genesis.json

      /opt/besu/bin/besu \
      --config-file=/config/config.toml \
      --p2p-host=$$(hostname -i) \
      --rpc-http-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} \
      --rpc-ws-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} ;

x-tessera-def: &tessera-def
  build:
    context: config/tessera
    args:
      TESSERA_VERSION: ${TESSERA_VERSION:-latest}
  environment:
    TESSERA_MODE: orion
  expose:
    - 9000
    - 9080
    - 9101
  restart: "no"
  healthcheck:
    test:
      [
        "CMD",
        "wget",
        "--spider",
        "--proxy",
        "off",
        "http://localhost:9000/upcheck"
      ]
    interval: 3s
    timeout: 3s
    retries: 20
    start_period: 5s

services:

  validator1:
    <<: *besu-def
    ports:
      - 21001:8545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator1,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator1:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    networks:
      qatar-blockchain-poc:
        ipv4_address: 172.16.239.11

  validator2:
    <<: *besu-def
    ports:
      - 21002:8545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator2,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator2:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
    networks:
      qatar-blockchain-poc:
        ipv4_address: 172.16.239.12

  validator3:
    <<: *besu-def
    ports:
      - 21003:8545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator3,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator3:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
    networks:
      qatar-blockchain-poc:
        ipv4_address: 172.16.239.13

  validator4:
    <<: *besu-def
    ports:
      - 21004:8545/tcp
      - 30303
      - 9545
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=validator4,service.version=${BESU_VERSION:-latest}
    labels:
      - "consensus=besu"
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/validator4:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
    networks:
      qatar-blockchain-poc:
        ipv4_address: 172.16.239.14

  rpcnode:
    <<: *besu-def
    container_name: rpcnode
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=rpcnode,service.version=${BESU_VERSION:-latest}
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/rpcnode:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
    ports:
      - 8545:8545/tcp
      - 8546:8546/tcp
    networks:
      qatar-blockchain-poc:
        ipv4_address: 172.16.239.15

  moe-tessera:
    <<: *tessera-def
    ports:
      - 9081:9080
    volumes:
      - ./config/nodes/moe:/config/keys
      - ./logs/tessera:/var/log/tessera/
    networks:
      qatar-blockchain-poc:
        ipv4_address: 172.16.239.26

  moe-besu:
    <<: *besu-def
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=moe-besu,service.version=${BESU_VERSION:-latest}
      - NODE_ID=6
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/config/config.toml \
        --p2p-host=$$(hostname -i) \
        --privacy-enabled \
        --privacy-url=http://moe-tessera:9101 \
        --privacy-public-key-file=/opt/besu/keys/tm.pub \
        --privacy-onchain-groups-enabled=${PRIVACY_ONCHAIN_GROUPS_ENABLED:-false} \
        --rpc-http-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} \
        --rpc-ws-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} ;
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/moe:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
      - moe-tessera
    ports:
      - 20000:8545/tcp
      - 20001:8546/tcp
    networks:
      qatar-blockchain-poc:
        ipv4_address: 172.16.239.16

  mcit-tessera:
    <<: *tessera-def
    ports:
      - 9082:9080
    volumes:
      - ./config/nodes/mcit:/config/keys
      - ./logs/tessera:/var/log/tessera/
    networks:
      qatar-blockchain-poc:
        ipv4_address: 172.16.239.27

  mcit-besu:
    <<: *besu-def
    environment:
      - OTEL_RESOURCE_ATTRIBUTES=service.name=mcit-besu,service.version=${BESU_VERSION:-latest}
      - NODE_ID=7
    entrypoint:
      - /bin/bash
      - -c
      - |
        /opt/besu/bin/besu \
        --config-file=/config/config.toml \
        --p2p-host=$$(hostname -i) \
        --privacy-enabled \
        --privacy-url=http://mcit-tessera:9101 \
        --privacy-public-key-file=/opt/besu/keys/tm.pub \
        --privacy-onchain-groups-enabled=${PRIVACY_ONCHAIN_GROUPS_ENABLED:-false} \
        --rpc-http-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} \
        --rpc-ws-api=EEA,WEB3,ETH,NET,TRACE,DEBUG,ADMIN,TXPOOL,PRIV,PERM,${BESU_CONS_ALGO:-QBFT} ;
    volumes:
      - ./config/besu/:/config
      - ./config/nodes/mcit:/opt/besu/keys
      - ./logs/besu:/tmp/besu
    depends_on:
      - validator1
      - mcit-tessera
    ports:
      - 20002:8545/tcp
      - 20003:8546/tcp
    networks:
      qatar-blockchain-poc:
        ipv4_address: 172.16.239.17

volumes:
  public-keys:

networks:
  qatar-blockchain-poc:
    name: qatar-blockchain-poc
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24
